# Generated by Django 5.1.3 on 2024-11-09 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='default_city',
        ),
    ]
