# Generated by Django 5.1.3 on 2024-11-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0007_delete_default_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='default_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
    ]
