# Generated by Django 5.1.3 on 2024-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_cityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
    ]
