# Generated by Django 5.1.3 on 2024-11-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_search_citymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_citymodel',
            old_name='city_name',
            new_name='city_name_form',
        ),
    ]
